/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.compiladores;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jose5
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setBackground(new Color(0,0,0,0));

        checkAndEnableButton();
        
                // Habilitar la funcionalidad de arrastrar y soltar
        // Habilitar la funcionalidad de arrastrar y soltar
        DropTarget dropTarget = new DropTarget(areaxml, new DropTargetAdapter() {
            @Override
            public void drop(DropTargetDropEvent event) {
                try {
                    Transferable transferable = event.getTransferable();
                    if (transferable.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                        event.acceptDrop(DnDConstants.ACTION_COPY);
                        java.util.List fileList = (java.util.List) transferable.getTransferData(DataFlavor.javaFileListFlavor);
                        for (Object file : fileList) {
                            if (file instanceof java.io.File) {
                                String filePath = ((java.io.File) file).getAbsolutePath();
                                if (filePath.toLowerCase().endsWith(".xml")) {
                                    rutaXML.setText(filePath);
                                    checkAndEnableButton();
                                    break; // Solo aceptar el primer archivo .xml encontrado
                                } else {
                                    checkAndEnableButton();
                                    DialogError Derror = new DialogError();
                                    Derror.setTxtdialogo("Por favor, arrastra un archivo XML");
                                    Derror.setVisible(true);
                                }
                            }
                        }
                        event.dropComplete(true);
                    } else {
                        event.rejectDrop();
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    event.rejectDrop();
                }
            }
        });
    }
    
    private void openDialog() {
        JFileChooser jFileChooser = new JFileChooser("src\\Files");
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser.setDialogTitle("Seleccione un archivo");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos XML", "xml"); 
        jFileChooser.setFileFilter(filter); //para añadir filtro solo muestre archivos .xml

        if (jFileChooser.showOpenDialog(this) != JFileChooser.CANCEL_OPTION) {
            rutaXML.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            checkAndEnableButton();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_11 = new Swing.Panel_1();
        button1 = new Swing.Button();
        button2 = new Swing.Button();
        jSeparator1 = new javax.swing.JSeparator();
        panelCustom1 = new Swing.PanelCustom();
        rutaXML = new Swing.TextField();
        button3 = new Swing.Button();
        jLabel2 = new javax.swing.JLabel();
        areaxml = new javax.swing.JLabel();
        btnBorrar = new Swing.Button();
        btnanalizar = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        panel_11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(255, 102, 102));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cruz (1).png"))); // NOI18N
        button1.setShadowColor(new java.awt.Color(51, 51, 51));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel_11.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        button2.setBackground(new java.awt.Color(255, 255, 204));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/angulo-pequeno-hacia-abajo.png"))); // NOI18N
        button2.setShadowColor(new java.awt.Color(51, 51, 51));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel_11.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_11.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1597, 392, 50, 10));

        rutaXML.setShadowColor(new java.awt.Color(51, 51, 51));
        rutaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaXMLActionPerformed(evt);
            }
        });
        panelCustom1.add(rutaXML);
        rutaXML.setBounds(20, 50, 610, 50);

        button3.setBackground(new java.awt.Color(153, 255, 153));
        button3.setText("Agregar");
        button3.setFont(new java.awt.Font("Segoe UI Variable", 1, 15)); // NOI18N
        button3.setShadowColor(new java.awt.Color(51, 51, 51));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelCustom1.add(button3);
        button3.setBounds(630, 50, 100, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Agrega el .XML");
        panelCustom1.add(jLabel2);
        jLabel2.setBounds(30, 30, 120, 21);

        areaxml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cargarXML.png"))); // NOI18N
        panelCustom1.add(areaxml);
        areaxml.setBounds(30, 110, 750, 130);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        btnBorrar.setShadowColor(new java.awt.Color(51, 51, 51));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        panelCustom1.add(btnBorrar);
        btnBorrar.setBounds(730, 50, 60, 50);

        panel_11.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 831, 270));

        btnanalizar.setBackground(new java.awt.Color(153, 255, 153));
        btnanalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cargando.png"))); // NOI18N
        btnanalizar.setText("Analizar");
        btnanalizar.setFont(new java.awt.Font("Segoe UI Variable", 1, 15)); // NOI18N
        btnanalizar.setShadowColor(new java.awt.Color(51, 51, 51));
        btnanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalizarActionPerformed(evt);
            }
        });
        panel_11.add(btnanalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logoUMG.png"))); // NOI18N
        panel_11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 420, 400));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Analizador XML");
        panel_11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_11, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_11, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_button2ActionPerformed

    private void rutaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaXMLActionPerformed

    private void btnanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalizarActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("cmd /c start navegador.html");
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnanalizarActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        try {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException  ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }       
        openDialog();
    }//GEN-LAST:event_button3ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        rutaXML.setText("");
        checkAndEnableButton();
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void checkAndEnableButton() {
    // Habilitar el botón solo si hay texto en el TextField
    if (rutaXML.getText().trim().isEmpty()) {
        btnanalizar.setEnabled(false);
        btnanalizar.setBackground(new java.awt.Color(204,204,204));
    } else {
        btnanalizar.setEnabled(true);
        btnanalizar.setBackground(new java.awt.Color(153,255,153));
    }
}
    
    @Override
public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
   getImage(ClassLoader.getSystemResource("img/xml.png"));
   return retValue;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaxml;
    private Swing.Button btnBorrar;
    private Swing.Button btnanalizar;
    private Swing.Button button1;
    private Swing.Button button2;
    private Swing.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private Swing.PanelCustom panelCustom1;
    private Swing.Panel_1 panel_11;
    private Swing.TextField rutaXML;
    // End of variables declaration//GEN-END:variables
}
